process_map:
  ee_3j:
    mg_subprocess_name: P0_epem_uuxg
    mg_born_subprocess_name: P1_epem_uuxg
    diagrams_file: config/diagrams/eeuug.json
  ee_4j:
    mg_subprocess_name: P0_epem_uuxgg
    mg_born_subprocess_name: P1_epem_uuxgg
    diagrams_file: config/diagrams/eeuugg.json


mg_subprocess_name: ${integrator.process_map.${process}[mg_subprocess_name]}
mg_born_subprocess_name: ${integrator.process_map.${process}[mg_born_subprocess_name]}
diagrams_file: ${integrator.process_map.${process}[diagrams_file]}


e_cm: 1000.

############################################################################
### MG won't allow to use the same apis locally and in cluster #############
############# so modify following line accordingly #########################
api_base: ${hydra:runtime.cwd}/src/integration/matrix_element/process_api_storage/${process}
###########################################################################

cross_sections:
  nlo:
    class: NLOCrossSection
    multithread_cores: 64 # total multithreads
    api_path:       ${integrator.api_base}/loop/SubProcesses/${integrator.mg_subprocess_name}/api.so
#    api_path_born:  ${integrator.api_base}/born/SubProcesses/${integrator.mg_born_subprocess_name}/api.so
    api_path_coll:  ${integrator.api_base}/counterterms/SubProcesses/${integrator.mg_subprocess_name}/api_collinear_integrated.so
    api_path_soft:  ${integrator.api_base}/counterterms/SubProcesses/${integrator.mg_subprocess_name}/api_soft_integrated.so
    api_path_real:  ${integrator.api_base}/counterterms/SubProcesses/${integrator.mg_subprocess_name}/api_sreal.so